[bot_detection]
# IP based rate limiting
ip_limit = 2.0
ip_window = 600

# Bot detection by user agent
user_agent_limit = 100.0
user_agent_window = 3600

# Link bot detection (e.g. search engines, archivers)
link_limit = 20.0
link_window = 600
